In [1]:
import numpy as np



In [2]:
# Create array, matrix, and tensor

arr = np.array([1, 2, 3, 4, 5])

mat = np.array([[1, 2, 3], [4, 5, 6]])
tensor = np.array([[[1, 2], [3, 4]]])
# print(arr, "\n", mat, "\n", tensor)

arr, mat, tensor




(array([1, 2, 3, 4, 5]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[1, 2],
         [3, 4]]]))

In [3]:
# shape of array, matrix, and tensor

print(arr.shape, mat.shape, tensor.shape)


(5,) (2, 3) (1, 2, 2)


In [4]:
# Reshaping 

reshaped_arr = arr.reshape(5, 1)
reshaped_arr
reshaped_arr.shape



(5, 1)

In [5]:
# Tnsor

arr_to_tnsor = arr.reshape(1, 5, 1)
arr_to_tnsor


array([[[1],
        [2],
        [3],
        [4],
        [5]]])

In [6]:
abc = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
abc
abc.shape


(1, 3, 3)

In [7]:
# concatenation:

l1 = np.array([1, 2, 3, 4])
l2 = np.array([11, 12, 13, 14])
cl = np.concatenate((l1, l2))
cl


array([ 1,  2,  3,  4, 11, 12, 13, 14])

In [8]:
# Mathematical operations:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
sum = a + b
print(a, "+", b, "=", sum)

minus = a - b
print(a, "-", b, "=",  minus)

multiplication = a * b
print(a, "*", b, "=", multiplication)

division = a / b
print(a, "/", b, "=", division)

int_division = a // b
print(a, "//", b, "=", int_division)

c = np.array([12])

d = a + c
d

e = b + 10
e
# data broadcasting: when we perform operations on arrays of different shapes, numpy will automatically broadcast the smaller array to match the shape of the larger array. This allows for element-wise operations to be performed without explicitly reshaping the arrays.





[1 2 3] + [4 5 6] = [5 7 9]
[1 2 3] - [4 5 6] = [-3 -3 -3]
[1 2 3] * [4 5 6] = [ 4 10 18]
[1 2 3] / [4 5 6] = [0.25 0.4  0.5 ]
[1 2 3] // [4 5 6] = [0 0 0]


array([14, 15, 16])

In [9]:
# Selection and indexing:

# slicing: we can select a subset of an array.
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)
print(a.shape)

b = a.reshape(9, 1)

print(b[2:7])
print()
print(b[2: 6: 2]) 

c = b.copy()
c = c.reshape(1, 9)
print(c)
print(c.shape)
print(c[1:6])
print()

d = c.copy()
d = d.reshape(9, 1)
print(d)
print(d.shape)
print()

print(d[1:5])
print()

print(d[1:6:2])
print()

print(d[d > 3])



[1 2 3 4 5 6 7 8 9]
(9,)
[[3]
 [4]
 [5]
 [6]
 [7]]

[[3]
 [5]]
[[1 2 3 4 5 6 7 8 9]]
(1, 9)
[]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(9, 1)

[[2]
 [3]
 [4]
 [5]]

[[2]
 [4]
 [6]]

[4 5 6 7 8 9]


In [10]:
# Math functions:

x = np.array([1, 2, 3, 4, 5, 6, 7, 8])

sum_x = np.sum(x)
sum_x



np.int64(36)

In [11]:
num_list = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

max_numberList = np.max(num_list)
print("The Maximum number is: ",max_numberList)


The Maximum number is:  9


In [12]:
# Create a random matrix:

rand_mat = np.random.randint(0, 9, (3, 4))
rand_mat
print(f"The Random_matrix is:\n {rand_mat}")



The Random_matrix is:
 [[3 8 3 5]
 [5 5 2 7]
 [4 4 0 1]]


In [13]:
# Vstack

x = np.array([1, 2, 3, 4])
y =  np.array([5, 6, 7, 8])
stacking_xy = np.vstack((x, y))
print("The created matrix by X and Y: \n",stacking_xy)
print("The Shape of matrix: " ,stacking_xy.shape)



The created matrix by X and Y: 
 [[1 2 3 4]
 [5 6 7 8]]
The Shape of matrix:  (2, 4)


In [14]:
# hstack:

x = np.array([2, 4, 6, 8])
y = np.array([1, 3, 5, 7])
print(f"X: {x}, and Y: {y} ")
z = np.hstack((x, y))
print("The Hstacking of X and Y = \n", z)
print("The shape of matrix: ", z.shape)
z2 = z.reshape(1, 8)
print(z2)
print(z2.shape)

X: [2 4 6 8], and Y: [1 3 5 7] 
The Hstacking of X and Y = 
 [2 4 6 8 1 3 5 7]
The shape of matrix:  (8,)
[[2 4 6 8 1 3 5 7]]
(1, 8)


In [ ]:
# Data Normalization:

x = np.array([2, 4, 6, 8, 10, 12])
print(f"The X is: {x}")

mean_x = np.mean(x)
print(f"The Mean of X is:  \t {mean_x}")

std_x = np.std(x)
print(f"The Standard debiation of X is {std_x}")

norm_x = (x - mean_x) /std_x
print(f"The X has normalized to: \n {norm_x}")

mean__norm_x = np.mean(norm_x)
print(f"The means of Norm_x is: \n {round(mean__norm_x, 2)} ")

std__norm_x = np.std(norm_x)
print(f"The standard debiation of norm_X is: \n {std__norm_x}")

""" The Data normalization is:
    The means of norm_x shuld be 0.0
    and The std of norm_x shuld be 1.0

"""





The X is: [ 2  4  6  8 10 12]
The Mean of X is:  	 7.0
The Standard debiation of X is 3.415650255319866
The X has normalized to: 
 [-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]
The means of Norm_x is: 
 -0.0 
The standard debiation of norm_X is: 
 1.0
